name: Unittest Py2

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 2.7
        uses: actions/setup-python@v3
        with:
          python-version: "2.7"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest bk_iam django
      - name: Test with pytest
        run: |
          pytest ./tests/test_client.py ./tests/test_django.py
