name: Unittest Py3

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.6
        uses: actions/setup-python@v3
        with:
          python-version: "3.6"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install "django>=3,<4"
          pip install -r requirements.txt
          pip install -r requirements_dev.txt
      - name: Test with pytest
        run: |
          pytest --cov=bk_audit
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
